### ISSUE TITLE
Is this compatible with the things network 

### ISSUE THREAD

**Issue by izdrail** [Makerfabs/Project_Soil-Moisture-Sensor-Wifi#1]
SO I bought 2 of these sensors
Are they compatible with the thing network 
Can I register them as applications?
I've tried uploading an example from the things network library 
but I'm getting 

```
Arduino: 1.8.14 Hourly Build 2021/03/09 09:33 (Windows 10), Board: "Arduino Pro or Pro Mini, ATmega328P (3.3V, 8 MHz)"
src/TheThingsNode.h:17:10: fatal error: TheThingsNetwork.h: No such file or directory

 #include "TheThingsNetwork.h"

          ^~~~~~~~~~~~~~~~~~~~

compilation terminated.

exit status 1

Error compiling for board Arduino Pro or Pro Mini.



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

So are these sensors compatible or I need to follow the the example provided by you ?

**Comment by 195cn** [comment]
Hi ,
We can only provide basic code about sx1278.

You can try [https://github.com/Makerfabs/Lora-Soil-Moisture-Sensor](https://github.com/Makerfabs/Lora-Soil-Moisture-Sensor)
It can communate each other via Lora.

About the ThingsWork library, maybe is LoraWan，we are not sure if we support it and cannot offer further help.
If you want connect sensor to Internet, I suggest thinkabout MakePython Lora. It can connect to WiFi using ESP32.

**Comment by IKutsar** [comment]
HI,
I need a support regarding Python files for ESP for LoRa MakeFabs Soil Moisture solution. Is anybody who can help?
